<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ApplicationSeeder extends Seeder
{
    /**
     * Snapshot of the real applicants, applications, and their related records currently in the system.
     */
    public function run(): void
    {
        // Applicant accounts (must come before applications, which reference them)
        DB::table('applicants')->insert([
            [
                'id' => 1,
                'name' => 'Cedric Domanais',
                'email' => 'zeddomanais0421@gmail.com',
                'password' => '$2y$12$HwxbU49/3tQAzQUD.GiBFuQfS9n.9LWMpZrvAmU7vFVW2oUrpRqjK',
                'remember_token' => null,
                'created_at' => '2026-09-01 10:06:15',
                'updated_at' => '2026-09-03 10:52:40',
            ],
            [
                'id' => 5,
                'name' => 'QS Test',
                'email' => 'qstest1788251704@example.com',
                'password' => '$2y$12$2POQg7E.F57.h/z/P1UuDuCbWwENdzCV4P5WDYsGmvw1yjZSX/FcW',
                'remember_token' => null,
                'created_at' => '2026-09-01 16:35:05',
                'updated_at' => '2026-09-01 16:35:05',
            ],
        ]);

        DB::table('applications')->insert([
            [
                'id' => 1,
                'job_position_id' => 1,
                'applicant_id' => null,
                'status' => 'evaluated',
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-08-26 10:09:04',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 2,
                'job_position_id' => 6,
                'applicant_id' => null,
                'status' => 'disqualified',
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-08-26 11:05:47',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 4,
                'job_position_id' => 1,
                'applicant_id' => null,
                'status' => 'pending',
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-08-26 10:07:10',
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
            ],
            [
                'id' => 5,
                'job_position_id' => 6,
                'applicant_id' => null,
                'status' => 'pending',
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-08-26 10:07:10',
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
            ],
            [
                'id' => 7,
                'job_position_id' => 1,
                'applicant_id' => null,
                'status' => 'qualified',
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
            ],
            [
                'id' => 8,
                'job_position_id' => 6,
                'applicant_id' => null,
                'status' => 'qualified',
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
            ],
            [
                'id' => 9,
                'job_position_id' => 1,
                'applicant_id' => null,
                'status' => 'qualified',
                'created_at' => '2026-07-13 07:53:42',
                'updated_at' => '2026-08-19 14:38:24',
                'resume_checked' => 1,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 16,
                'job_position_id' => 8,
                'applicant_id' => null,
                'status' => 'evaluated',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-08-26 10:48:50',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 17,
                'job_position_id' => 1,
                'applicant_id' => null,
                'status' => 'evaluated',
                'created_at' => '2026-08-19 10:01:51',
                'updated_at' => '2026-08-25 10:23:16',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 18,
                'job_position_id' => 9,
                'applicant_id' => null,
                'status' => 'pending',
                'created_at' => '2026-08-19 10:07:26',
                'updated_at' => '2026-08-25 10:08:05',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 23,
                'job_position_id' => 8,
                'applicant_id' => null,
                'status' => 'disqualified',
                'created_at' => '2026-08-19 11:12:50',
                'updated_at' => '2026-08-19 14:10:33',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 38,
                'job_position_id' => 40,
                'applicant_id' => 1,
                'status' => 'qualified',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 12:37:39',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 52,
                'job_position_id' => 9,
                'applicant_id' => 1,
                'status' => 'disqualified',
                'created_at' => '2026-09-01 15:54:47',
                'updated_at' => '2026-09-01 16:21:03',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 58,
                'job_position_id' => 1,
                'applicant_id' => 5,
                'status' => 'disqualified',
                'created_at' => '2026-09-01 16:35:05',
                'updated_at' => '2026-09-01 17:09:57',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 79,
                'job_position_id' => 8,
                'applicant_id' => 1,
                'status' => 'pending',
                'created_at' => '2026-09-01 17:05:35',
                'updated_at' => '2026-09-01 17:05:35',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
            [
                'id' => 87,
                'job_position_id' => 6,
                'applicant_id' => 1,
                'status' => 'pending',
                'created_at' => '2026-09-03 13:47:12',
                'updated_at' => '2026-09-03 13:47:12',
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
            ],
        ]);

        DB::table('applicant_profiles')->insert([
            [
                'id' => 1,
                'application_id' => 1,
                'full_name' => 'Maria Santos',
                'email' => 'maria.santos@example.com',
                'phone' => '09171234501',
                'address' => 'Legazpi City, Albay',
                'birth_date' => null,
                'sex' => null,
                'civil_status' => null,
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-07-21 07:53:42',
            ],
            [
                'id' => 2,
                'application_id' => 2,
                'full_name' => 'Carlo Reyes',
                'email' => 'carlo.reyes@example.com',
                'phone' => '09171234502',
                'address' => 'Daraga, Albay',
                'birth_date' => null,
                'sex' => null,
                'civil_status' => null,
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-07-20 07:53:42',
            ],
            [
                'id' => 4,
                'application_id' => 4,
                'full_name' => 'Joshua Navarro',
                'email' => 'joshua.navarro@example.com',
                'phone' => '09171234504',
                'address' => 'Ligao City, Albay',
                'birth_date' => null,
                'sex' => null,
                'civil_status' => null,
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-07-18 07:53:42',
            ],
            [
                'id' => 5,
                'application_id' => 5,
                'full_name' => 'Patricia Gomez',
                'email' => 'patricia.gomez@example.com',
                'phone' => '09171234505',
                'address' => 'Guinobatan, Albay',
                'birth_date' => null,
                'sex' => null,
                'civil_status' => null,
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-07-17 07:53:42',
            ],
            [
                'id' => 7,
                'application_id' => 7,
                'full_name' => 'Elaine Flores',
                'email' => 'elaine.flores@example.com',
                'phone' => '09171234507',
                'address' => 'Naga City, Camarines Sur',
                'birth_date' => null,
                'sex' => null,
                'civil_status' => null,
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 8,
                'application_id' => 8,
                'full_name' => 'Miguel Bautista',
                'email' => 'miguel.bautista@example.com',
                'phone' => '09171234508',
                'address' => 'Pili, Camarines Sur',
                'birth_date' => null,
                'sex' => null,
                'civil_status' => null,
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
            ],
            [
                'id' => 9,
                'application_id' => 9,
                'full_name' => 'Noel Garcia',
                'email' => 'noel.garcia@example.com',
                'phone' => '09171234509',
                'address' => 'Masbate City, Masbate',
                'birth_date' => null,
                'sex' => null,
                'civil_status' => null,
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-13 07:53:42',
                'updated_at' => '2026-07-13 07:53:42',
            ],
            [
                'id' => 13,
                'application_id' => 16,
                'full_name' => 'Ethyl Alcohol',
                'email' => 'ethyl@gmail.com',
                'phone' => '09954005628',
                'address' => 'Kapitolyo, Pasig, Metro Manila',
                'birth_date' => '1999-01-01',
                'sex' => 'Female',
                'civil_status' => 'Single',
                'religion' => 'Roman Catholic',
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 14,
                'application_id' => 17,
                'full_name' => 'xqwefxwfc',
                'email' => 'vqwfqwvffsdf@gmail.com',
                'phone' => '50114984180',
                'address' => 'adadcaawfcwf',
                'birth_date' => '2026-08-14',
                'sex' => 'Female',
                'civil_status' => 'Single',
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-08-19 10:01:51',
                'updated_at' => '2026-08-19 10:01:51',
            ],
            [
                'id' => 15,
                'application_id' => 18,
                'full_name' => 'sagsaegdgd',
                'email' => 'sfsafdfasf@gmail.com',
                'phone' => '8494848048',
                'address' => 'safdfasfsaf',
                'birth_date' => '2026-08-06',
                'sex' => null,
                'civil_status' => 'Married',
                'religion' => null,
                'disability' => null,
                'ethnic_group' => null,
                'created_at' => '2026-08-19 10:07:26',
                'updated_at' => '2026-08-19 10:07:26',
            ],
            [
                'id' => 20,
                'application_id' => 23,
                'full_name' => 'asdfasgasg',
                'email' => 'asgasdfgag@gmail.com',
                'phone' => '564489489',
                'address' => 'safsadfasf',
                'birth_date' => '2026-08-06',
                'sex' => 'Male',
                'civil_status' => 'Separated',
                'religion' => 'fdasfsdfasf',
                'disability' => 'sdfsadf',
                'ethnic_group' => 'sdfsdfsaf',
                'created_at' => '2026-08-19 11:12:50',
                'updated_at' => '2026-08-19 11:12:50',
            ],
            [
                'id' => 27,
                'application_id' => 38,
                'full_name' => 'Cedric U. Domanais',
                'email' => 'zeddomanais0421@gmail.com',
                'phone' => '09954005381',
                'address' => 'Guilid, Ligao City',
                'birth_date' => '2001-08-04',
                'sex' => 'Male',
                'civil_status' => 'Single',
                'religion' => 'Roman Catholic',
                'disability' => 'N/A',
                'ethnic_group' => 'N/A',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 28,
                'application_id' => 52,
                'full_name' => 'Cedric U. Domanais',
                'email' => 'zeddomanais0421@gmail.com',
                'phone' => '09954005381',
                'address' => 'Guilid, Ligao City',
                'birth_date' => '2001-08-04',
                'sex' => 'Male',
                'civil_status' => 'Single',
                'religion' => 'Roman Catholic',
                'disability' => 'N/A',
                'ethnic_group' => 'N/A',
                'created_at' => '2026-09-01 15:54:47',
                'updated_at' => '2026-09-01 15:54:47',
            ],
            [
                'id' => 30,
                'application_id' => 79,
                'full_name' => 'Cedric U. Domanais',
                'email' => 'zeddomanais0421@gmail.com',
                'phone' => '09954005381',
                'address' => 'Guilid, Ligao City',
                'birth_date' => '2001-08-04',
                'sex' => 'Male',
                'civil_status' => 'Single',
                'religion' => 'Roman Catholic',
                'disability' => 'N/A',
                'ethnic_group' => 'N/A',
                'created_at' => '2026-09-01 17:05:35',
                'updated_at' => '2026-09-03 13:15:15',
            ],
            [
                'id' => 33,
                'application_id' => 87,
                'full_name' => 'Cedric U. Domanais',
                'email' => 'zeddomanais0421@gmail.com',
                'phone' => '09954005381',
                'address' => 'Guilid, Ligao City',
                'birth_date' => '2001-08-04',
                'sex' => 'Male',
                'civil_status' => 'Single',
                'religion' => 'Roman Catholic',
                'disability' => 'N/A',
                'ethnic_group' => 'N/A',
                'created_at' => '2026-09-03 13:47:12',
                'updated_at' => '2026-09-03 16:16:44',
            ],
        ]);

        DB::table('applicant_educations')->insert([
            [
                'id' => 1,
                'application_id' => 1,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'Bicol University',
                'degree' => 'Bachelor of Elementary Education',
                'year_graduated' => '2022',
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-07-21 07:53:42',
            ],
            [
                'id' => 2,
                'application_id' => 2,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'Divine Word College of Legazpi',
                'degree' => 'Bachelor of Science in Office Administration',
                'year_graduated' => '2023',
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-07-20 07:53:42',
            ],
            [
                'id' => 4,
                'application_id' => 4,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'Bicol University',
                'degree' => 'Bachelor of Secondary Education',
                'year_graduated' => '2021',
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-07-18 07:53:42',
            ],
            [
                'id' => 5,
                'application_id' => 5,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'University of Santo Tomas-Legazpi',
                'degree' => 'Bachelor of Science in Business Administration',
                'year_graduated' => '2020',
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-07-17 07:53:42',
            ],
            [
                'id' => 7,
                'application_id' => 7,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'Ateneo de Naga University',
                'degree' => 'Bachelor of Elementary Education',
                'year_graduated' => '2018',
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 8,
                'application_id' => 8,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'Camarines Sur Polytechnic Colleges',
                'degree' => 'Bachelor of Science in Information Technology',
                'year_graduated' => '2020',
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
            ],
            [
                'id' => 9,
                'application_id' => 9,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'Masbate Colleges',
                'degree' => 'Bachelor of Arts',
                'year_graduated' => '2022',
                'created_at' => '2026-07-13 07:53:42',
                'updated_at' => '2026-07-13 07:53:42',
            ],
            [
                'id' => 13,
                'application_id' => 16,
                'level' => 'College',
                'level_specify' => null,
                'school' => 'University of Santo Tomas Legazpi',
                'degree' => 'Bachelor of Science in Education',
                'year_graduated' => '2024',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 14,
                'application_id' => 17,
                'level' => 'Bachelor\'s Degree',
                'level_specify' => null,
                'school' => 'sdfasdfasfasf',
                'degree' => 'sdfsadfas',
                'year_graduated' => '1411',
                'created_at' => '2026-08-19 10:01:51',
                'updated_at' => '2026-08-19 10:01:51',
            ],
            [
                'id' => 15,
                'application_id' => 18,
                'level' => 'Other\'s',
                'level_specify' => 'fasdfsadfasfs',
                'school' => 'asdfasfafdsaf',
                'degree' => 'fasdfsafsaf',
                'year_graduated' => '2025',
                'created_at' => '2026-08-19 10:07:26',
                'updated_at' => '2026-08-19 10:07:26',
            ],
            [
                'id' => 16,
                'application_id' => 23,
                'level' => 'Other\'s',
                'level_specify' => 'fsdfasdf',
                'school' => 'sdfsadfsdaf',
                'degree' => 'dsfasdafasf',
                'year_graduated' => '2030',
                'created_at' => '2026-08-19 11:12:50',
                'updated_at' => '2026-08-19 11:12:50',
            ],
            [
                'id' => 19,
                'application_id' => 38,
                'level' => 'Bachelor\'s Degree',
                'level_specify' => null,
                'school' => 'Divine Word College of Legazpi',
                'degree' => 'Bachelor of Science in Information Technology',
                'year_graduated' => '2025',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 28,
                'application_id' => 79,
                'level' => 'Bachelor\'s Degree',
                'level_specify' => null,
                'school' => 'Divine Word College of Legazpi',
                'degree' => 'Bachelor of Science in Information Technology',
                'year_graduated' => '2025',
                'created_at' => '2026-09-03 13:15:15',
                'updated_at' => '2026-09-03 13:15:15',
            ],
        ]);

        DB::table('applicant_experiences')->insert([
            [
                'id' => 1,
                'application_id' => 1,
                'title' => 'Substitute Teacher',
                'company' => 'Legazpi Elementary School',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '1 year',
                'details' => 'Sample work experience generated by the application seeder.',
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-07-21 07:53:42',
            ],
            [
                'id' => 2,
                'application_id' => 2,
                'title' => 'Office Clerk',
                'company' => 'ABC Trading',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '8 months',
                'details' => 'Sample work experience generated by the application seeder.',
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-07-20 07:53:42',
            ],
            [
                'id' => 4,
                'application_id' => 4,
                'title' => 'Private School Teacher',
                'company' => 'Saint Michael Academy',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '3 years',
                'details' => 'Sample work experience generated by the application seeder.',
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-07-18 07:53:42',
            ],
            [
                'id' => 5,
                'application_id' => 5,
                'title' => 'Administrative Aide',
                'company' => 'Municipal Government Office',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '4 years',
                'details' => 'Sample work experience generated by the application seeder.',
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-07-17 07:53:42',
            ],
            [
                'id' => 7,
                'application_id' => 7,
                'title' => 'Teacher',
                'company' => 'Naga Learning Center',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '5 years',
                'details' => 'Sample work experience generated by the application seeder.',
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 8,
                'application_id' => 8,
                'title' => 'Administrative Staff',
                'company' => 'Provincial Government Office',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '3 years',
                'details' => 'Sample work experience generated by the application seeder.',
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
            ],
            [
                'id' => 9,
                'application_id' => 9,
                'title' => 'Tutor',
                'company' => 'Private Tutorial Center',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '2 year',
                'details' => 'Sample work experience generated by the application seeder.',
                'created_at' => '2026-07-13 07:53:42',
                'updated_at' => '2026-07-30 07:04:26',
            ],
            [
                'id' => 13,
                'application_id' => 16,
                'title' => 'Administrative Assistant II',
                'company' => 'Bureau of Internal Revenue',
                'first_day' => null,
                'last_day' => null,
                'years_months' => '1',
                'details' => 'Tax Complain',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 14,
                'application_id' => 17,
                'title' => 'fasdfasdf',
                'company' => 'fsdfasdfasf',
                'first_day' => null,
                'last_day' => null,
                'years_months' => null,
                'details' => 'asdfasdfasdfaf',
                'created_at' => '2026-08-19 10:01:51',
                'updated_at' => '2026-08-19 10:01:51',
            ],
            [
                'id' => 15,
                'application_id' => 18,
                'title' => 'safasdfsadf',
                'company' => 'sadfsdfaf',
                'first_day' => null,
                'last_day' => null,
                'years_months' => null,
                'details' => 'sadfsdfsfsdf',
                'created_at' => '2026-08-19 10:07:26',
                'updated_at' => '2026-08-19 10:07:26',
            ],
            [
                'id' => 16,
                'application_id' => 23,
                'title' => 'sfsadfsdaf',
                'company' => 'sdfsafsadfs',
                'first_day' => null,
                'last_day' => null,
                'years_months' => null,
                'details' => 'dfsafsafasfdawsf',
                'created_at' => '2026-08-19 11:12:50',
                'updated_at' => '2026-08-19 11:12:50',
            ],
            [
                'id' => 21,
                'application_id' => 38,
                'title' => 'Government Internship Program',
                'company' => 'Department of Labor and Employment',
                'first_day' => 'January 2025',
                'last_day' => 'December 2025',
                'years_months' => null,
                'details' => 'Provides administrative and operational support to the office by assisting in data encoding, records management, document preparation, client assistance, program activities, field profiling, and other non-technical tasks. Participates in training, seminars, and government programs while performing duties under the supervision of designated DOLE personnel.',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
        ]);

        DB::table('applicant_trainings')->insert([
            [
                'id' => 1,
                'application_id' => 1,
                'title' => 'Classroom Management Seminar',
                'hours' => 16,
                'training_date' => null,
                'training_end_date' => null,
                'details' => 'Sample training record generated for testing.',
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-07-21 07:53:42',
            ],
            [
                'id' => 2,
                'application_id' => 2,
                'title' => 'Records Management Training',
                'hours' => 8,
                'training_date' => null,
                'training_end_date' => null,
                'details' => 'Sample training record generated for testing.',
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-07-20 07:53:42',
            ],
            [
                'id' => 4,
                'application_id' => 4,
                'title' => 'Teaching Strategies Workshop',
                'hours' => 24,
                'training_date' => null,
                'training_end_date' => null,
                'details' => 'Sample training record generated for testing.',
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-07-18 07:53:42',
            ],
            [
                'id' => 5,
                'application_id' => 5,
                'title' => 'Government Records Administration',
                'hours' => 16,
                'training_date' => null,
                'training_end_date' => null,
                'details' => 'Sample training record generated for testing.',
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-07-17 07:53:42',
            ],
            [
                'id' => 7,
                'application_id' => 7,
                'title' => 'Inclusive Education Training',
                'hours' => 40,
                'training_date' => null,
                'training_end_date' => null,
                'details' => 'Sample training record generated for testing.',
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 8,
                'application_id' => 8,
                'title' => 'Office Productivity Tools',
                'hours' => 24,
                'training_date' => null,
                'training_end_date' => null,
                'details' => 'Sample training record generated for testing.',
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
            ],
            [
                'id' => 9,
                'application_id' => 9,
                'title' => 'Basic Teaching Workshop',
                'hours' => 8,
                'training_date' => '2026-07-01',
                'training_end_date' => null,
                'details' => 'Sample training record generated for testing.',
                'created_at' => '2026-07-13 07:53:42',
                'updated_at' => '2026-07-30 07:05:36',
            ],
            [
                'id' => 12,
                'application_id' => 16,
                'title' => 'Tax Compliance Seminar',
                'hours' => 48,
                'training_date' => '2021-08-01',
                'training_end_date' => null,
                'details' => null,
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 13,
                'application_id' => 9,
                'title' => 'Practice Teaching',
                'hours' => 8,
                'training_date' => '2026-03-01',
                'training_end_date' => null,
                'details' => null,
                'created_at' => '2026-07-30 07:05:18',
                'updated_at' => '2026-07-30 07:05:54',
            ],
            [
                'id' => 14,
                'application_id' => 17,
                'title' => 'asdfsadfsadfsaf',
                'hours' => 45,
                'training_date' => '2026-08-01',
                'training_end_date' => null,
                'details' => null,
                'created_at' => '2026-08-19 10:01:51',
                'updated_at' => '2026-08-19 10:01:51',
            ],
            [
                'id' => 15,
                'application_id' => 18,
                'title' => 'sdafsdfasf',
                'hours' => 55,
                'training_date' => '2026-06-01',
                'training_end_date' => null,
                'details' => null,
                'created_at' => '2026-08-19 10:07:26',
                'updated_at' => '2026-08-19 10:07:26',
            ],
            [
                'id' => 17,
                'application_id' => 23,
                'title' => 'fasdfsadfa',
                'hours' => 88,
                'training_date' => '2026-03-01',
                'training_end_date' => '2026-05-01',
                'details' => null,
                'created_at' => '2026-08-19 11:12:50',
                'updated_at' => '2026-08-19 11:12:50',
            ],
            [
                'id' => 20,
                'application_id' => 38,
                'title' => 'Occupational Safety and Health (OSH) Seminar',
                'hours' => 24,
                'training_date' => '2026-08-01',
                'training_end_date' => '2026-08-01',
                'details' => null,
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
        ]);

        DB::table('applicant_eligibilities')->insert([
            [
                'id' => 1,
                'application_id' => 1,
                'license_name' => 'Licensure Examination for Teachers',
                'license_specify' => null,
                'rating' => '84.50',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-07-21 07:53:42',
            ],
            [
                'id' => 2,
                'application_id' => 2,
                'license_name' => 'Civil Service Professional',
                'license_specify' => null,
                'rating' => '82.10',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-07-20 07:53:42',
            ],
            [
                'id' => 4,
                'application_id' => 4,
                'license_name' => 'Licensure Examination for Teachers',
                'license_specify' => null,
                'rating' => '88.20',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-07-18 07:53:42',
            ],
            [
                'id' => 5,
                'application_id' => 5,
                'license_name' => 'Civil Service Professional',
                'license_specify' => null,
                'rating' => '85.10',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-07-17 07:53:42',
            ],
            [
                'id' => 7,
                'application_id' => 7,
                'license_name' => 'Licensure Examination for Teachers',
                'license_specify' => null,
                'rating' => '91.50',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 8,
                'application_id' => 8,
                'license_name' => 'Civil Service Professional',
                'license_specify' => null,
                'rating' => '87.30',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
            ],
            [
                'id' => 11,
                'application_id' => 16,
                'license_name' => 'License Professional Teacher',
                'license_specify' => null,
                'rating' => '90',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 12,
                'application_id' => 17,
                'license_name' => 'CSCS Professional',
                'license_specify' => null,
                'rating' => '99',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-08-19 10:01:51',
                'updated_at' => '2026-08-19 10:01:51',
            ],
            [
                'id' => 13,
                'application_id' => 18,
                'license_name' => 'Other\'s',
                'license_specify' => 'asdfasdfaf',
                'rating' => '100',
                'date_issued' => null,
                'valid_until' => null,
                'never_expires' => 0,
                'created_at' => '2026-08-19 10:07:26',
                'updated_at' => '2026-08-19 10:07:26',
            ],
            [
                'id' => 17,
                'application_id' => 23,
                'license_name' => 'Other\'s',
                'license_specify' => 'rtgergegeg',
                'rating' => '99.5',
                'date_issued' => '2026-08-12',
                'valid_until' => null,
                'never_expires' => 1,
                'created_at' => '2026-08-19 11:12:50',
                'updated_at' => '2026-08-19 11:12:50',
            ],
            [
                'id' => 20,
                'application_id' => 38,
                'license_name' => 'CSC Professional',
                'license_specify' => null,
                'rating' => '98',
                'date_issued' => '2022-07-15',
                'valid_until' => '2025-07-15',
                'never_expires' => 0,
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
        ]);

        DB::table('application_documents')->insert([
            [
                'id' => 11,
                'application_id' => 16,
                'type' => 'letter_of_intent',
                'file_path' => 'documents/GB2orPBnqhOocX0F64SaOO3CwPRZ5XDDT7UuZ8Y7.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 12,
                'application_id' => 16,
                'type' => 'tor_diploma',
                'file_path' => 'documents/uAcWPFy59EAcHAXsVmScAS8JyhX8OxKicjHKWaCp.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 13,
                'application_id' => 16,
                'type' => 'prc_license',
                'file_path' => 'documents/cDcsdm7gtmZNJmq2v9i7S8rJIlV9G5FKmwfdQm6P.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 14,
                'application_id' => 16,
                'type' => 'eligibility_file',
                'file_path' => 'documents/dJ8e93dY4rczuy5QIuJEibNdMysJGVFMv8v3TrMI.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 15,
                'application_id' => 16,
                'type' => 'training_certificates',
                'file_path' => 'documents/29cuMzpLbKIrWfaL68HwsBNwEsE23NuVKRzwj9dZ.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 16,
                'application_id' => 16,
                'type' => 'employment_records',
                'file_path' => 'documents/djonfUtq4vQkV3VkN4a3WmXRfboEZngHdDjWrDkR.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 17,
                'application_id' => 16,
                'type' => 'latest_appointment',
                'file_path' => 'documents/FQVaRpyrgrl1vUpccyJ6RWgNFJsXd5UUVicxZJJH.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 18,
                'application_id' => 16,
                'type' => 'performance_rating',
                'file_path' => 'documents/RvLBYv8I0I4tOnoJYpUiD1rmHesTOxBWzccDzqxj.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 19,
                'application_id' => 16,
                'type' => 'cav',
                'file_path' => 'documents/48L4YBkRpLB2HDmZ0983dSlsuQWXQytpVYISE2dc.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 20,
                'application_id' => 16,
                'type' => 'movs',
                'file_path' => 'documents/moPFO3sOSyZMlnnEj7tpEnrETvuTCFn9apt533pV.pdf',
                'created_at' => '2026-07-27 07:22:46',
                'updated_at' => '2026-07-27 07:22:46',
            ],
            [
                'id' => 24,
                'application_id' => 9,
                'type' => 'Diploma',
                'file_path' => 'applications/documents/01KYS1N369YYR6998SMN38ESHW.pdf',
                'created_at' => '2026-07-30 08:18:32',
                'updated_at' => '2026-07-30 08:18:32',
            ],
            [
                'id' => 25,
                'application_id' => 1,
                'type' => 'Transcript',
                'file_path' => 'applications/documents/01KYS1X68X4CWVA8J5934AR0D7.pdf',
                'created_at' => '2026-07-30 08:22:57',
                'updated_at' => '2026-07-30 08:22:57',
            ],
            [
                'id' => 28,
                'application_id' => 38,
                'type' => 'letter_of_intent',
                'file_path' => 'documents/OS8bV3NDAGkUSTQwAwoe2cW1q1wRU1kKiNfPx8Ud.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 29,
                'application_id' => 38,
                'type' => 'tor_diploma',
                'file_path' => 'documents/vnbyUgMhHZyCFZdOlLotfTsDDNgcudCc3NKpau5X.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 30,
                'application_id' => 38,
                'type' => 'prc_license',
                'file_path' => 'documents/hKQYzrTzAVxMGPMozTiNo4UOKyEsBJ089Qaa8Q3q.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 31,
                'application_id' => 38,
                'type' => 'eligibility_file',
                'file_path' => 'documents/ySyPbnNWDrnoCpJ8uMZziL3fHMoXdrWP6ENKoKkS.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 32,
                'application_id' => 38,
                'type' => 'training_certificates',
                'file_path' => 'documents/XFxaZQEyqlZmOnIyi0fytuD8yIU9VaD16b24idu9.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 33,
                'application_id' => 38,
                'type' => 'performance_rating',
                'file_path' => 'documents/eOTlEvHilDK5zYfezYk4WzmBKFDzmXB9PiN5SFC8.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 34,
                'application_id' => 38,
                'type' => 'cav',
                'file_path' => 'documents/Heqf8ZCMSyBShlpYEyaJbxlShVW0jN1ZeqMNMfA6.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 35,
                'application_id' => 38,
                'type' => 'movs',
                'file_path' => 'documents/rgAiCySckmkCrRHIZuuQVjQ9N4Y41Ig2mWGhNGkQ.pdf',
                'created_at' => '2026-09-01 10:25:59',
                'updated_at' => '2026-09-01 10:25:59',
            ],
            [
                'id' => 36,
                'application_id' => 52,
                'type' => 'letter_of_intent',
                'file_path' => 'documents/9yrA41fdYE3v3JrtTRE8b4jwRXblaX47Q20jJG9H.pdf',
                'created_at' => '2026-09-01 15:54:47',
                'updated_at' => '2026-09-01 15:54:47',
            ],
            [
                'id' => 39,
                'application_id' => 79,
                'type' => 'letter_of_intent',
                'file_path' => 'documents/FSmnoyzvTz36yJv3hGd3lscaoygT8wsyTld9PLGr.pdf',
                'created_at' => '2026-09-01 17:05:35',
                'updated_at' => '2026-09-01 17:05:35',
            ],
            [
                'id' => 40,
                'application_id' => 79,
                'type' => 'tor_diploma',
                'file_path' => 'documents/2AbiHvQc96XPtPG5qVQmlKMOD5W3PBRttYub922E.pdf',
                'created_at' => '2026-09-01 17:05:35',
                'updated_at' => '2026-09-01 17:05:35',
            ],
            [
                'id' => 41,
                'application_id' => 79,
                'type' => 'prc_license',
                'file_path' => 'documents/TzYwvbtkH91atsUOKkSvmvSv5kNTE2uw97w7AgP6.pdf',
                'created_at' => '2026-09-01 17:06:00',
                'updated_at' => '2026-09-01 17:06:00',
            ],
            [
                'id' => 42,
                'application_id' => 79,
                'type' => 'eligibility_file',
                'file_path' => 'documents/gZcFLHYSmB0ygigoEeyN8W5HtbKLn0p8hblIh6YR.pdf',
                'created_at' => '2026-09-01 17:08:19',
                'updated_at' => '2026-09-01 17:08:19',
            ],
        ]);

        DB::table('application_control_numbers')->insert([
            [
                'id' => 1,
                'application_id' => 1,
                'control_number' => 'Alb-T-I-1624-2026',
                'generated_by' => 2,
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 2,
                'application_id' => 2,
                'control_number' => 'Alb-ADAS II-1650-2026',
                'generated_by' => 2,
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 4,
                'application_id' => 4,
                'control_number' => 'Alb-T-I-9690-2026',
                'generated_by' => 2,
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 5,
                'application_id' => 5,
                'control_number' => 'Alb-ADAS II-2198-2026',
                'generated_by' => 2,
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 7,
                'application_id' => 7,
                'control_number' => 'Alb-T-I-6437-2026',
                'generated_by' => 2,
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 8,
                'application_id' => 8,
                'control_number' => 'Alb-ADAS II-2390-2026',
                'generated_by' => 2,
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 9,
                'application_id' => 9,
                'control_number' => 'Alb-T-I-7872-2026',
                'generated_by' => 2,
                'created_at' => '2026-07-13 07:53:42',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 12,
                'application_id' => 16,
                'control_number' => 'Alb-HT I-1359-2026',
                'generated_by' => 5,
                'created_at' => '2026-08-10 01:18:04',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 13,
                'application_id' => 17,
                'control_number' => 'Alb-T-I-3891-2026',
                'generated_by' => 5,
                'created_at' => '2026-08-25 09:55:43',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 20,
                'application_id' => 38,
                'control_number' => 'Alb-ADA I-7537-2026',
                'generated_by' => 5,
                'created_at' => '2026-09-01 10:30:37',
                'updated_at' => '2026-09-03 13:55:11',
            ],
            [
                'id' => 74,
                'application_id' => 18,
                'control_number' => 'Alb-TA1-7666-2026',
                'generated_by' => 5,
                'created_at' => '2026-09-01 15:39:53',
                'updated_at' => '2026-09-03 13:52:36',
            ],
            [
                'id' => 75,
                'application_id' => 52,
                'control_number' => 'Alb-TA1-7798-2026',
                'generated_by' => null,
                'created_at' => '2026-09-01 15:54:47',
                'updated_at' => '2026-09-03 13:52:36',
            ],
            [
                'id' => 78,
                'application_id' => 79,
                'control_number' => 'Alb-HT I-9965-2026',
                'generated_by' => null,
                'created_at' => '2026-09-01 17:05:35',
                'updated_at' => '2026-09-03 13:52:36',
            ],
            [
                'id' => 79,
                'application_id' => 87,
                'control_number' => 'Alb-ADAS II-8445-2026',
                'generated_by' => null,
                'created_at' => '2026-09-03 13:47:12',
                'updated_at' => '2026-09-03 13:52:36',
            ],
        ]);

        DB::table('application_evaluations')->insert([
            [
                'id' => 9,
                'application_id' => 1,
                'documentary_mandatory' => '["letter_of_intent", "pds_work_experience", "eligibility_certificate", "checklist_omnibus_sworn", "academic_records"]',
                'documentary_other' => '["training_certificates", "employment_certificate", "other_movs"]',
                'qs_education_met' => 1,
                'qs_experience_met' => 1,
                'qs_training_met' => 1,
                'qs_eligibility_met' => 1,
                'result' => 'qualified',
                'evaluator_id' => 5,
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 1,
                'remarks' => null,
                'evaluated_at' => '2026-08-26 10:09:04',
                'created_at' => '2026-07-27 06:17:17',
                'updated_at' => '2026-08-26 10:09:04',
            ],
            [
                'id' => 11,
                'application_id' => 2,
                'documentary_mandatory' => '["pds_work_experience", "letter_of_intent", "eligibility_certificate", "checklist_omnibus_sworn", "academic_records"]',
                'documentary_other' => '[]',
                'qs_education_met' => 0,
                'qs_experience_met' => 0,
                'qs_training_met' => 0,
                'qs_eligibility_met' => 0,
                'result' => 'excluded',
                'evaluator_id' => 5,
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 0,
                'remarks' => null,
                'evaluated_at' => '2026-08-26 09:00:58',
                'created_at' => '2026-07-30 08:49:59',
                'updated_at' => '2026-08-26 10:32:11',
            ],
            [
                'id' => 1,
                'application_id' => 4,
                'documentary_mandatory' => null,
                'documentary_other' => null,
                'qs_education_met' => null,
                'qs_experience_met' => null,
                'qs_training_met' => null,
                'qs_eligibility_met' => null,
                'result' => 'pending_document_review',
                'evaluator_id' => 3,
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
                'remarks' => 'Documents complete. Recommended for admin approval.',
                'evaluated_at' => null,
                'created_at' => '2026-07-19 07:53:42',
                'updated_at' => '2026-09-01 11:25:17',
            ],
            [
                'id' => 2,
                'application_id' => 5,
                'documentary_mandatory' => null,
                'documentary_other' => null,
                'qs_education_met' => null,
                'qs_experience_met' => null,
                'qs_training_met' => null,
                'qs_eligibility_met' => null,
                'result' => 'pending_document_review',
                'evaluator_id' => 3,
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
                'remarks' => 'Qualified and recommended for further processing.',
                'evaluated_at' => null,
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-09-01 11:25:17',
            ],
            [
                'id' => 4,
                'application_id' => 7,
                'documentary_mandatory' => null,
                'documentary_other' => null,
                'qs_education_met' => null,
                'qs_experience_met' => null,
                'qs_training_met' => null,
                'qs_eligibility_met' => null,
                'result' => 'pending_document_review',
                'evaluator_id' => 3,
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
                'remarks' => 'Application approved by the administrator.',
                'evaluated_at' => null,
                'created_at' => '2026-07-16 07:53:42',
                'updated_at' => '2026-09-01 11:25:17',
            ],
            [
                'id' => 5,
                'application_id' => 8,
                'documentary_mandatory' => null,
                'documentary_other' => null,
                'qs_education_met' => null,
                'qs_experience_met' => null,
                'qs_training_met' => null,
                'qs_eligibility_met' => null,
                'result' => 'pending_document_review',
                'evaluator_id' => 3,
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
                'remarks' => 'Qualified applicant. Application approved.',
                'evaluated_at' => null,
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-09-01 11:25:17',
            ],
            [
                'id' => 6,
                'application_id' => 9,
                'documentary_mandatory' => null,
                'documentary_other' => null,
                'qs_education_met' => null,
                'qs_experience_met' => null,
                'qs_training_met' => null,
                'qs_eligibility_met' => null,
                'result' => 'pending_document_review',
                'evaluator_id' => 5,
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
                'remarks' => null,
                'evaluated_at' => null,
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-09-01 11:25:17',
            ],
            [
                'id' => 10,
                'application_id' => 16,
                'documentary_mandatory' => '["letter_of_intent", "pds_work_experience", "eligibility_certificate", "checklist_omnibus_sworn", "academic_records"]',
                'documentary_other' => '["prc_license", "training_certificates", "employment_certificate", "performance_rating", "latest_appointment", "other_movs"]',
                'qs_education_met' => 1,
                'qs_experience_met' => 1,
                'qs_training_met' => 1,
                'qs_eligibility_met' => 1,
                'result' => 'qualified',
                'evaluator_id' => 5,
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 1,
                'remarks' => 'afsffafdsf',
                'evaluated_at' => '2026-08-26 10:49:14',
                'created_at' => '2026-07-27 07:36:53',
                'updated_at' => '2026-08-26 10:49:14',
            ],
            [
                'id' => 14,
                'application_id' => 17,
                'documentary_mandatory' => '["academic_records", "eligibility_certificate", "letter_of_intent", "pds_work_experience", "checklist_omnibus_sworn"]',
                'documentary_other' => '["latest_appointment", "employment_certificate", "prc_license"]',
                'qs_education_met' => 1,
                'qs_experience_met' => 1,
                'qs_training_met' => 1,
                'qs_eligibility_met' => 1,
                'result' => 'qualified',
                'evaluator_id' => 5,
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 1,
                'remarks' => 'nice one
',
                'evaluated_at' => '2026-08-25 17:30:42',
                'created_at' => '2026-08-19 13:33:00',
                'updated_at' => '2026-08-25 17:30:42',
            ],
            [
                'id' => 12,
                'application_id' => 18,
                'documentary_mandatory' => null,
                'documentary_other' => null,
                'qs_education_met' => null,
                'qs_experience_met' => null,
                'qs_training_met' => null,
                'qs_eligibility_met' => null,
                'result' => 'pending_document_review',
                'evaluator_id' => 5,
                'resume_checked' => 1,
                'credentials_valid' => 1,
                'recommended' => 1,
                'remarks' => 'Recommended
',
                'evaluated_at' => null,
                'created_at' => '2026-08-19 10:08:19',
                'updated_at' => '2026-09-01 11:25:17',
            ],
            [
                'id' => 13,
                'application_id' => 23,
                'documentary_mandatory' => null,
                'documentary_other' => null,
                'qs_education_met' => null,
                'qs_experience_met' => null,
                'qs_training_met' => null,
                'qs_eligibility_met' => null,
                'result' => 'pending_document_review',
                'evaluator_id' => 5,
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
                'remarks' => 'No CSC',
                'evaluated_at' => null,
                'created_at' => '2026-08-19 11:13:19',
                'updated_at' => '2026-09-01 11:25:17',
            ],
            [
                'id' => 79,
                'application_id' => 38,
                'documentary_mandatory' => '["letter_of_intent", "pds_work_experience", "eligibility_certificate", "checklist_omnibus_sworn", "academic_records"]',
                'documentary_other' => '["prc_license", "performance_rating", "employment_certificate", "training_certificates"]',
                'qs_education_met' => 1,
                'qs_experience_met' => 1,
                'qs_training_met' => 1,
                'qs_eligibility_met' => 1,
                'result' => 'qualified',
                'evaluator_id' => 5,
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 1,
                'remarks' => 'all requirements are Qualified',
                'evaluated_at' => '2026-09-01 12:37:04',
                'created_at' => '2026-09-01 10:33:35',
                'updated_at' => '2026-09-01 12:37:04',
            ],
            [
                'id' => 80,
                'application_id' => 52,
                'documentary_mandatory' => '["letter_of_intent", "pds_work_experience", "eligibility_certificate", "checklist_omnibus_sworn", "academic_records"]',
                'documentary_other' => '["prc_license", "training_certificates", "employment_certificate", "performance_rating", "latest_appointment", "other_movs"]',
                'qs_education_met' => 1,
                'qs_experience_met' => 1,
                'qs_training_met' => 0,
                'qs_eligibility_met' => 0,
                'result' => 'not_qualified',
                'evaluator_id' => 5,
                'resume_checked' => 0,
                'credentials_valid' => 0,
                'recommended' => 0,
                'remarks' => 'Qualifications did not meet',
                'evaluated_at' => '2026-09-01 16:20:15',
                'created_at' => '2026-09-01 16:19:06',
                'updated_at' => '2026-09-01 16:20:15',
            ],
        ]);

        DB::table('application_status_logs')->insert([
            [
                'id' => 1,
                'application_id' => 1,
                'status' => 'pending',
                'remarks' => 'Application submitted successfully.',
                'changed_by' => null,
                'created_at' => '2026-07-21 07:53:42',
                'updated_at' => '2026-07-21 07:53:42',
            ],
            [
                'id' => 2,
                'application_id' => 2,
                'status' => 'pending',
                'remarks' => 'Application submitted successfully.',
                'changed_by' => null,
                'created_at' => '2026-07-20 07:53:42',
                'updated_at' => '2026-07-20 07:53:42',
            ],
            [
                'id' => 4,
                'application_id' => 4,
                'status' => 'pending',
                'remarks' => 'Application submitted successfully.',
                'changed_by' => null,
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-07-18 07:53:42',
            ],
            [
                'id' => 5,
                'application_id' => 4,
                'status' => 'evaluated',
                'remarks' => 'Documents complete. Recommended for admin approval.',
                'changed_by' => 3,
                'created_at' => '2026-07-19 07:53:42',
                'updated_at' => '2026-07-19 07:53:42',
            ],
            [
                'id' => 6,
                'application_id' => 5,
                'status' => 'pending',
                'remarks' => 'Application submitted successfully.',
                'changed_by' => null,
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-07-17 07:53:42',
            ],
            [
                'id' => 7,
                'application_id' => 5,
                'status' => 'evaluated',
                'remarks' => 'Qualified and recommended for further processing.',
                'changed_by' => 3,
                'created_at' => '2026-07-18 07:53:42',
                'updated_at' => '2026-07-18 07:53:42',
            ],
            [
                'id' => 10,
                'application_id' => 7,
                'status' => 'pending',
                'remarks' => 'Application submitted successfully.',
                'changed_by' => null,
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 11,
                'application_id' => 7,
                'status' => 'evaluated',
                'remarks' => 'Application approved by the administrator.',
                'changed_by' => 3,
                'created_at' => '2026-07-16 07:53:42',
                'updated_at' => '2026-07-16 07:53:42',
            ],
            [
                'id' => 12,
                'application_id' => 7,
                'status' => 'approved',
                'remarks' => 'Application approved by the administrator.',
                'changed_by' => 2,
                'created_at' => '2026-07-17 07:53:42',
                'updated_at' => '2026-07-17 07:53:42',
            ],
            [
                'id' => 13,
                'application_id' => 8,
                'status' => 'pending',
                'remarks' => 'Application submitted successfully.',
                'changed_by' => null,
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
            ],
            [
                'id' => 14,
                'application_id' => 8,
                'status' => 'evaluated',
                'remarks' => 'Qualified applicant. Application approved.',
                'changed_by' => 3,
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 15,
                'application_id' => 8,
                'status' => 'approved',
                'remarks' => 'Qualified applicant. Application approved.',
                'changed_by' => 2,
                'created_at' => '2026-07-16 07:53:42',
                'updated_at' => '2026-07-16 07:53:42',
            ],
            [
                'id' => 16,
                'application_id' => 9,
                'status' => 'pending',
                'remarks' => 'Application submitted successfully.',
                'changed_by' => null,
                'created_at' => '2026-07-13 07:53:42',
                'updated_at' => '2026-07-13 07:53:42',
            ],
            [
                'id' => 17,
                'application_id' => 9,
                'status' => 'evaluated',
                'remarks' => 'Required teaching eligibility was not submitted.',
                'changed_by' => 3,
                'created_at' => '2026-07-14 07:53:42',
                'updated_at' => '2026-07-14 07:53:42',
            ],
            [
                'id' => 18,
                'application_id' => 9,
                'status' => 'rejected',
                'remarks' => 'Required teaching eligibility was not submitted.',
                'changed_by' => 2,
                'created_at' => '2026-07-15 07:53:42',
                'updated_at' => '2026-07-15 07:53:42',
            ],
            [
                'id' => 25,
                'application_id' => 9,
                'status' => 'evaluated',
                'remarks' => 'passed the practical teaching exam',
                'changed_by' => 5,
                'created_at' => '2026-07-30 07:20:56',
                'updated_at' => '2026-07-30 07:20:56',
            ],
            [
                'id' => 26,
                'application_id' => 9,
                'status' => 'approved',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-07-30 07:21:16',
                'updated_at' => '2026-07-30 07:21:16',
            ],
            [
                'id' => 27,
                'application_id' => 9,
                'status' => 'evaluated',
                'remarks' => 'disqualify due to fraud',
                'changed_by' => 5,
                'created_at' => '2026-07-30 07:22:15',
                'updated_at' => '2026-07-30 07:22:15',
            ],
            [
                'id' => 28,
                'application_id' => 9,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-07-30 07:23:01',
                'updated_at' => '2026-07-30 07:23:01',
            ],
            [
                'id' => 29,
                'application_id' => 16,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-07-30 08:21:37',
                'updated_at' => '2026-07-30 08:21:37',
            ],
            [
                'id' => 30,
                'application_id' => 1,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-07-30 08:27:36',
                'updated_at' => '2026-07-30 08:27:36',
            ],
            [
                'id' => 31,
                'application_id' => 9,
                'status' => 'evaluated',
                'remarks' => 'disqualify due to fraud',
                'changed_by' => 5,
                'created_at' => '2026-07-30 08:28:23',
                'updated_at' => '2026-07-30 08:28:23',
            ],
            [
                'id' => 32,
                'application_id' => 9,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-07-30 08:28:46',
                'updated_at' => '2026-07-30 08:28:46',
            ],
            [
                'id' => 33,
                'application_id' => 18,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-19 10:22:28',
                'updated_at' => '2026-08-19 10:22:28',
            ],
            [
                'id' => 34,
                'application_id' => 18,
                'status' => 'evaluated',
                'remarks' => 'Recommended
',
                'changed_by' => 5,
                'created_at' => '2026-08-19 10:24:14',
                'updated_at' => '2026-08-19 10:24:14',
            ],
            [
                'id' => 35,
                'application_id' => 18,
                'status' => 'evaluated',
                'remarks' => 'Recommended
',
                'changed_by' => 5,
                'created_at' => '2026-08-19 10:24:35',
                'updated_at' => '2026-08-19 10:24:35',
            ],
            [
                'id' => 36,
                'application_id' => 23,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-19 13:32:39',
                'updated_at' => '2026-08-19 13:32:39',
            ],
            [
                'id' => 37,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'lack of files
',
                'changed_by' => 5,
                'created_at' => '2026-08-19 13:33:09',
                'updated_at' => '2026-08-19 13:33:09',
            ],
            [
                'id' => 38,
                'application_id' => 23,
                'status' => 'evaluated',
                'remarks' => 'No CSC',
                'changed_by' => 5,
                'created_at' => '2026-08-19 13:34:25',
                'updated_at' => '2026-08-19 13:34:25',
            ],
            [
                'id' => 39,
                'application_id' => 23,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 13:37:34',
                'updated_at' => '2026-08-19 13:37:34',
            ],
            [
                'id' => 40,
                'application_id' => 23,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:10:15',
                'updated_at' => '2026-08-19 14:10:15',
            ],
            [
                'id' => 41,
                'application_id' => 23,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:10:33',
                'updated_at' => '2026-08-19 14:10:33',
            ],
            [
                'id' => 42,
                'application_id' => 9,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:11:04',
                'updated_at' => '2026-08-19 14:11:04',
            ],
            [
                'id' => 43,
                'application_id' => 18,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:17:54',
                'updated_at' => '2026-08-19 14:17:54',
            ],
            [
                'id' => 44,
                'application_id' => 16,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:18:17',
                'updated_at' => '2026-08-19 14:18:17',
            ],
            [
                'id' => 45,
                'application_id' => 16,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:18:35',
                'updated_at' => '2026-08-19 14:18:35',
            ],
            [
                'id' => 46,
                'application_id' => 9,
                'status' => 'approved',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:37:51',
                'updated_at' => '2026-08-19 14:37:51',
            ],
            [
                'id' => 47,
                'application_id' => 9,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-19 14:38:08',
                'updated_at' => '2026-08-19 14:38:08',
            ],
            [
                'id' => 48,
                'application_id' => 9,
                'status' => 'approved',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-19 14:38:24',
                'updated_at' => '2026-08-19 14:38:24',
            ],
            [
                'id' => 50,
                'application_id' => 2,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-25 09:51:55',
                'updated_at' => '2026-08-25 09:51:55',
            ],
            [
                'id' => 51,
                'application_id' => 17,
                'status' => 'pending',
                'remarks' => 'Reverted from evaluated: no control number was assigned.',
                'changed_by' => null,
                'created_at' => '2026-08-25 09:54:00',
                'updated_at' => '2026-08-25 09:54:00',
            ],
            [
                'id' => 53,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'Corrected: control number was already assigned but status had not been updated (assigned before the status-sync fix).',
                'changed_by' => null,
                'created_at' => '2026-08-25 10:00:58',
                'updated_at' => '2026-08-25 10:00:58',
            ],
            [
                'id' => 54,
                'application_id' => 18,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-25 10:01:30',
                'updated_at' => '2026-08-25 10:01:30',
            ],
            [
                'id' => 55,
                'application_id' => 18,
                'status' => 'pending',
                'remarks' => 'Corrected: no control number was assigned yet, status should not have been evaluated.',
                'changed_by' => null,
                'created_at' => '2026-08-25 10:08:05',
                'updated_at' => '2026-08-25 10:08:05',
            ],
            [
                'id' => 58,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'lack of files
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 10:15:32',
                'updated_at' => '2026-08-25 10:15:32',
            ],
            [
                'id' => 59,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'lack of files
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 10:16:00',
                'updated_at' => '2026-08-25 10:16:00',
            ],
            [
                'id' => 60,
                'application_id' => 17,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-25 10:21:02',
                'updated_at' => '2026-08-25 10:21:02',
            ],
            [
                'id' => 61,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-25 10:23:16',
                'updated_at' => '2026-08-25 10:23:16',
            ],
            [
                'id' => 62,
                'application_id' => 16,
                'status' => 'approved',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-25 10:27:58',
                'updated_at' => '2026-08-25 10:27:58',
            ],
            [
                'id' => 80,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'lack of files
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 14:00:37',
                'updated_at' => '2026-08-25 14:00:37',
            ],
            [
                'id' => 84,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 15:52:20',
                'updated_at' => '2026-08-25 15:52:20',
            ],
            [
                'id' => 85,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 15:52:48',
                'updated_at' => '2026-08-25 15:52:48',
            ],
            [
                'id' => 86,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 15:53:18',
                'updated_at' => '2026-08-25 15:53:18',
            ],
            [
                'id' => 88,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 15:59:42',
                'updated_at' => '2026-08-25 15:59:42',
            ],
            [
                'id' => 93,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 16:05:47',
                'updated_at' => '2026-08-25 16:05:47',
            ],
            [
                'id' => 94,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 16:07:17',
                'updated_at' => '2026-08-25 16:07:17',
            ],
            [
                'id' => 96,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:07:56',
                'updated_at' => '2026-08-25 17:07:56',
            ],
            [
                'id' => 99,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:19:27',
                'updated_at' => '2026-08-25 17:19:27',
            ],
            [
                'id' => 102,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:26:10',
                'updated_at' => '2026-08-25 17:26:10',
            ],
            [
                'id' => 103,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:27:48',
                'updated_at' => '2026-08-25 17:27:48',
            ],
            [
                'id' => 104,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:27:50',
                'updated_at' => '2026-08-25 17:27:50',
            ],
            [
                'id' => 105,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:27:58',
                'updated_at' => '2026-08-25 17:27:58',
            ],
            [
                'id' => 106,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:28:12',
                'updated_at' => '2026-08-25 17:28:12',
            ],
            [
                'id' => 107,
                'application_id' => 17,
                'status' => 'evaluated',
                'remarks' => 'nice one
',
                'changed_by' => 5,
                'created_at' => '2026-08-25 17:30:42',
                'updated_at' => '2026-08-25 17:30:42',
            ],
            [
                'id' => 108,
                'application_id' => 2,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-26 09:00:58',
                'updated_at' => '2026-08-26 09:00:58',
            ],
            [
                'id' => 109,
                'application_id' => 16,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-26 09:33:44',
                'updated_at' => '2026-08-26 09:33:44',
            ],
            [
                'id' => 110,
                'application_id' => 16,
                'status' => 'approved',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-26 09:56:05',
                'updated_at' => '2026-08-26 09:56:05',
            ],
            [
                'id' => 113,
                'application_id' => 1,
                'status' => 'pending',
                'remarks' => 'System correction: status recalculated to match QS evaluation outcome.',
                'changed_by' => null,
                'created_at' => '2026-08-26 10:07:10',
                'updated_at' => '2026-08-26 10:07:10',
            ],
            [
                'id' => 114,
                'application_id' => 2,
                'status' => 'pending',
                'remarks' => 'System correction: status recalculated to match QS evaluation outcome.',
                'changed_by' => null,
                'created_at' => '2026-08-26 10:07:10',
                'updated_at' => '2026-08-26 10:07:10',
            ],
            [
                'id' => 115,
                'application_id' => 4,
                'status' => 'pending',
                'remarks' => 'System correction: status recalculated to match QS evaluation outcome.',
                'changed_by' => null,
                'created_at' => '2026-08-26 10:07:10',
                'updated_at' => '2026-08-26 10:07:10',
            ],
            [
                'id' => 116,
                'application_id' => 5,
                'status' => 'pending',
                'remarks' => 'System correction: status recalculated to match QS evaluation outcome.',
                'changed_by' => null,
                'created_at' => '2026-08-26 10:07:10',
                'updated_at' => '2026-08-26 10:07:10',
            ],
            [
                'id' => 117,
                'application_id' => 1,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-26 10:09:04',
                'updated_at' => '2026-08-26 10:09:04',
            ],
            [
                'id' => 120,
                'application_id' => 2,
                'status' => 'excluded',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-26 10:32:11',
                'updated_at' => '2026-08-26 10:32:11',
            ],
            [
                'id' => 121,
                'application_id' => 16,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-26 10:37:23',
                'updated_at' => '2026-08-26 10:37:23',
            ],
            [
                'id' => 122,
                'application_id' => 16,
                'status' => 'pending',
                'remarks' => 'System correction: restore action was setting status to Evaluated unconditionally.',
                'changed_by' => null,
                'created_at' => '2026-08-26 10:41:43',
                'updated_at' => '2026-08-26 10:41:43',
            ],
            [
                'id' => 123,
                'application_id' => 16,
                'status' => 'evaluated',
                'remarks' => null,
                'changed_by' => 5,
                'created_at' => '2026-08-26 10:48:50',
                'updated_at' => '2026-08-26 10:48:50',
            ],
            [
                'id' => 124,
                'application_id' => 2,
                'status' => 'rejected',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-08-26 11:05:47',
                'updated_at' => '2026-08-26 11:05:47',
            ],
            [
                'id' => 126,
                'application_id' => 38,
                'status' => 'evaluated',
                'remarks' => 'Control number assigned.',
                'changed_by' => 5,
                'created_at' => '2026-09-01 10:30:37',
                'updated_at' => '2026-09-01 10:30:37',
            ],
            [
                'id' => 127,
                'application_id' => 38,
                'status' => 'pending',
                'remarks' => 'Corrected: control number assignment was incorrectly auto-setting status to Evaluated.',
                'changed_by' => null,
                'created_at' => '2026-09-01 10:37:55',
                'updated_at' => '2026-09-01 10:37:55',
            ],
            [
                'id' => 128,
                'application_id' => 38,
                'status' => 'evaluated',
                'remarks' => 'all requirements are Qualified',
                'changed_by' => 5,
                'created_at' => '2026-09-01 12:37:04',
                'updated_at' => '2026-09-01 12:37:04',
            ],
            [
                'id' => 129,
                'application_id' => 38,
                'status' => 'approved',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-09-01 12:37:39',
                'updated_at' => '2026-09-01 12:37:39',
            ],
            [
                'id' => 132,
                'application_id' => 52,
                'status' => 'evaluated',
                'remarks' => 'Qualifications did not meet',
                'changed_by' => 5,
                'created_at' => '2026-09-01 16:20:11',
                'updated_at' => '2026-09-01 16:20:11',
            ],
            [
                'id' => 133,
                'application_id' => 52,
                'status' => 'disqualified',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-09-01 16:21:03',
                'updated_at' => '2026-09-01 16:21:03',
            ],
            [
                'id' => 134,
                'application_id' => 58,
                'status' => 'disqualified',
                'remarks' => null,
                'changed_by' => 1,
                'created_at' => '2026-09-01 17:09:57',
                'updated_at' => '2026-09-01 17:09:57',
            ],
        ]);

    }
}
