<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobPositionSeeder extends Seeder
{
    /**
     * Snapshot of the real job positions currently in the system.
     */
    public function run(): void
    {
        DB::table('job_positions')->insert(
            [
            [
                'id' => 1,
                'title' => 'Teacher I',
                'description' => 'Entry-level teaching position for elementary education.',
                'salary_grade' => null,
                'monthly_salary' => null,
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 0,
                'posted_at' => '2026-07-22',
                'until' => null,
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-22 07:53:42',
                'updated_at' => '2026-08-20 13:43:48',
            ],
            [
                'id' => 2,
                'title' => 'Teacher II',
                'description' => 'Mid-level teaching position requiring experience.',
                'salary_grade' => '12',
                'monthly_salary' => null,
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 0,
                'posted_at' => '2026-07-22',
                'until' => null,
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-22 07:53:42',
                'updated_at' => '2026-08-20 13:44:48',
            ],
            [
                'id' => 3,
                'title' => 'School Clerk',
                'description' => 'Administrative support for school operations.',
                'salary_grade' => null,
                'monthly_salary' => null,
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 1,
                'posted_at' => '2026-07-22',
                'until' => null,
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-22 07:53:42',
                'updated_at' => '2026-08-24 09:55:27',
            ],
            [
                'id' => 4,
                'title' => 'Guidance Counselor',
                'description' => 'Provides student counseling and support services.',
                'salary_grade' => null,
                'monthly_salary' => null,
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 1,
                'posted_at' => '2026-08-04',
                'until' => '2026-08-27',
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-22 07:53:42',
                'updated_at' => '2026-08-20 13:55:48',
            ],
            [
                'id' => 5,
                'title' => 'Principal I',
                'description' => 'School head responsible for overall administration.',
                'salary_grade' => null,
                'monthly_salary' => null,
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 0,
                'posted_at' => '2026-07-22',
                'until' => null,
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-22 07:53:42',
                'updated_at' => '2026-08-24 09:55:36',
            ],
            [
                'id' => 6,
                'title' => 'Administrative Assistant II',
                'description' => 'Provides clerical, administrative, and records management support.',
                'salary_grade' => null,
                'monthly_salary' => null,
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 1,
                'posted_at' => '2026-07-22',
                'until' => null,
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-22 07:53:42',
                'updated_at' => '2026-07-30 08:42:14',
            ],
            [
                'id' => 8,
                'title' => 'Head Teacher I',
                'description' => 'Manages a school\'s daily operations, leads teaching and learning, and supports staff',
                'salary_grade' => '14',
                'monthly_salary' => '38764.00',
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 1,
                'posted_at' => '2026-07-27',
                'until' => null,
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-27 06:59:52',
                'updated_at' => '2026-07-27 07:15:07',
            ],
            [
                'id' => 9,
                'title' => 'Technical Assistant I',
                'description' => 'Support role typically hired under a Contract of Service (COS) to handle program implementation, draft official communications, and maintain databases for specific regional or division projects like school sports, health, or feeding programs',
                'salary_grade' => '10',
                'monthly_salary' => '29257.00',
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 1,
                'posted_at' => '2026-07-28',
                'until' => '2026-08-06',
                'until_time' => null,
                'attachment_path' => null,
                'csc_publication_path' => null,
                'created_at' => '2026-07-28 08:51:25',
                'updated_at' => '2026-08-20 14:09:51',
            ],
            [
                'id' => 27,
                'title' => 'dsfafdsa',
                'description' => 'fasdfasdfsdfs',
                'salary_grade' => null,
                'monthly_salary' => null,
                'education_requirement' => null,
                'training_requirement' => null,
                'experience_requirement' => null,
                'eligibility_requirement' => null,
                'is_open' => 1,
                'posted_at' => '2026-08-24',
                'until' => '2026-08-30',
                'until_time' => '17:00:00',
                'attachment_path' => 'job-positions/01M0RQT5EX79BEGSRCXG95BF0Z.pdf',
                'csc_publication_path' => 'job-positions/01M0RQT5F2HW2GS3VQ10594Z1X.pdf',
                'created_at' => '2026-08-24 09:57:56',
                'updated_at' => '2026-08-24 10:45:56',
            ],
            [
                'id' => 40,
                'title' => 'Admin Aide I',
                'description' => 'Provides basic clerical and administrative support, including filing and maintaining records, encoding data, preparing documents, receiving and routing communications, and performing routine office tasks. Performs other related duties as assigned by the immediate supervisor.',
                'salary_grade' => '1',
                'monthly_salary' => '14763.00',
                'education_requirement' => 'College Graduate',
                'training_requirement' => 'None required',
                'experience_requirement' => 'None required',
                'eligibility_requirement' => 'None required',
                'is_open' => 1,
                'posted_at' => '2026-08-24',
                'until' => '2026-08-31',
                'until_time' => '17:30:00',
                'attachment_path' => 'job-positions/01M0RV1MSTR3FVRFAREBJVA44G.pdf',
                'csc_publication_path' => 'job-positions/01M0RV1MSZ1VEQ1P8V94JCM92V.pdf',
                'created_at' => '2026-08-24 10:54:27',
                'updated_at' => '2026-08-24 10:54:27',
            ],
        ]
        );
    }
}
